name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 
    - name: Restore dependencies
      working-directory: TreasureMap
      run: dotnet restore
    - name: Build
      working-directory: TreasureMap
      run: dotnet build --no-restore
    - name: Setup Shell Environment
      run: |
        sudo apt-get update
        sudo apt-get install bash
    - name: Test
      working-directory: TreasureMap/TreasureMap.Tests
      shell: bash
      run: dotnet test --no-build --verbosity normal --logger "trx"
    - name: Publish Executable for Windows
      working-directory: TreasureMap
      run: |
        dotnet publish --configuration Release --output ./publish --runtime win-x64 --self-contained true
    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-executable
        path: TreasureMap/publish/
  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Version Tag
        id: version
        run: |
          VERSION="v1.0.$(date +%s)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Tagging release with version: $VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: "Automatic release generated after merging to main."
          draft: false
          prerelease: false
          token: ${{ secrets.GH_PAT }}

  upload_release_assets:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: published-executable
          path: ./artifacts

      - name: Upload Executable to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*
          token: ${{ secrets.GH_PAT }}
